<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ _jqx-icon jqx-icon-ui-hamon jqx-icon-c_8dd5cc</name>
   <tag></tag>
   <elementGuidId>0be19f44-8a94-4d5f-960a-6da99cfbbb3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='date1']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jqx-icon jqx-icon-ui-hamon jqx-icon-calendar jqx-icon-calendar-ui-hamon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date1&quot;)/div[@class=&quot;jqx-max-size jqx-position-relative&quot;]/div[@class=&quot;jqx-position-absolute jqx-action-button jqx-action-button-ui-hamon jqx-fill-state-normal jqx-fill-state-normal-ui-hamon jqx-rc-r jqx-rc-r-ui-hamon jqx-default jqx-default-ui-hamon&quot;]/div[@class=&quot;jqx-icon jqx-icon-ui-hamon jqx-icon-calendar jqx-icon-calendar-ui-hamon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='date1']/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
